[package]
name = "cp_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.14.4"
quote = "1.0.26"
syn = { version = "1.0.109", features = ["full"] }


[lib]
proc-macro = true
